### ISSUE TITLE
Assertion failure in prelexer

### ISSUE THREAD

**Issue by treinen** [colis-anr/morbig#40] opened 2018-08-30 12:32 UTC
on the corpus sid.amd64.main+contrib+non-free.2018-05-23:

    $ examples/scripts/debian-maintainer-scripts corpus
    Cleaning up ... done.
    Start parsing 31302 files.
    Fatal error: exception File "prelexerState.ml", line 287, characters 31-37: Assertion failed
    Command exited with non-zero status 2

I am trying to find out on which file this happens, but this is surprisingly not so easy.

**Comment by treinen** [comment] 2018-08-30 13:03
The failure occurs on the file cloud-init_0.7.9-5/postinst
[postinst.txt](https://github.com/colis-anr/morbig/files/2336241/postinst.txt)

**Comment by treinen** [comment] 2018-08-30 16:41
the same happens on libvirtodbc0_6.1.6+dfsg2-4+b1/postinst.

These are the only two failures of morbig on that corpus. The third parsing error (bluez) was due to an actual syntax error in the script which has been fixed in the latest version of the debian package.

**Comment by yurug** [comment] 2018-09-03 11:39
Can you check again? I was unable to reproduce the two unexpected rejections (cloud-init and libvirtodbc) with the current development version of morbig (commit bc9e91511366ba7fe6f79c2ba2a637d99cf31d8e). I do confirm the syntax error on bluez though.

**Comment by yurug** [comment] 2018-09-03 11:42
Sorry. My mistake. Fixed in 0fc8ae8d50acffcf30ef13c8cb22e6a5a9508a21

**Closed by yurug** 2018-09-03 11:42 UTC

**Comment by treinen** [comment] 2018-09-03 11:53
Confirmed, this is fixed. Morbig now runs smoothly on the entire corpus (besides the erroneous bluez script).

Thanks -Ralf.
